# Generated by Django 4.1.7 on 2023-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanken',
            name='datum',
            field=models.DateField(auto_now_add=True),
        ),
    ]
