# Generated by Django 4.1.7 on 2023-03-09 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanken', '0002_alter_tanken_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanken',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
