# Generated by Django 4.1.6 on 2023-03-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanken', '0004_alter_tanken_bemerkung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanken',
            options={'verbose_name_plural': 'Tankvorgänge'},
        ),
    ]
